apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: mysql-db
spec:
  containers:
  - name: mysql
    image: mysql:8
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: rootpassword
    ports:
      - containerPort: 3306

